// <auto-generated />
namespace ShiftGrid.Test.NET.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addTypes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addTypes));
        
        string IMigrationMetadata.Id
        {
            get { return "202202151313156_addTypes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
