// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Test.NETCore.EF;

#nullable disable

namespace Test.NETCore.Migrations
{
    [DbContext(typeof(DB))]
    [Migration("20220520062450_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ShiftGrid.Test.Shared.Models.TestItem", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"), 1L, 1);

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime2");

                    b.Property<long?>("ParentTestItemId")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("TypeId")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.HasIndex("ParentTestItemId");

                    b.HasIndex("TypeId");

                    b.ToTable("TestItems");
                });

            modelBuilder.Entity("ShiftGrid.Test.Shared.Models.Type", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"), 1L, 1);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Types");
                });

            modelBuilder.Entity("ShiftGrid.Test.Shared.Models.TestItem", b =>
                {
                    b.HasOne("ShiftGrid.Test.Shared.Models.TestItem", "ParentTestItem")
                        .WithMany("ChildTestItems")
                        .HasForeignKey("ParentTestItemId");

                    b.HasOne("ShiftGrid.Test.Shared.Models.Type", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId");

                    b.Navigation("ParentTestItem");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("ShiftGrid.Test.Shared.Models.TestItem", b =>
                {
                    b.Navigation("ChildTestItems");
                });
#pragma warning restore 612, 618
        }
    }
}
